# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


talents = {
  acrobatics: [
    { name: "Agile",
      pre_skills: "acrobatics 1 0", pre_talents: "",
      description: "You may re-roll one d20 when attempting an Acrobatics test, but you must accept the new result."
    },

    { name: "Healthy Paranoia",
      pre_skills: "acrobatics 2 0", pre_talents: "Savage_Instincts 1",
      description: "You have a natural sense for when your life might be endangered. When involved in a struggle to resist being surprised, you gain 2 bonus Momentum."
    },

    { name: "Message Runner",       max_ranks: 2,
      pre_skills: "",               pre_talents: "Agile 1",
      description: "Couriers and message runners must get through the harshest conditions, across land that even goats would balk at. They learn to recognize the environment and to move naturally in response to it, taking advantage of the terrain’s effects. For each rank of Message Runner, you can reduce by 1 the Difficulty of any Acrobatics tests made to overcome obstacles, hindrances, hazards, and other forms of difficult terrain."
    },

    { name: "Nimble as a Cat",      max_ranks: 2,
      pre_skills: "",               pre_talents: "Agile 1",
      description: "Whether a career thief or just naturally graceful, you can leap extraordinary distances or suffer falls without harm. When making an Acrobatics test to jump or leap, reduce the Difficulty by one step for every rank of Nimble as a Cat. This may eliminate the need for the skill test if the result is reduced to Simple (D0). In addition, for each rank of Nimble as a Cat you gain 2 additional Armor Soak dice when suffering falling damage."
    },

    { name: "Pantherish Twist",
      pre_skills: "",               pre_talents: "Nimble_as_a_Cat 1",
      description: "When attempting a Defend reaction using the Acrobatics skill, you may reduce the amount of Doom generated by 1, to a minimum of 0."
    },

    { name: "Savage Instincts",
      pre_skills: "",               pre_talents: "Agile 1",
      description: "You are constantly in motion and difficult to hit with ranged attacks. If you use a minor or standard action to move during your turn, any ranged attacks targeted against you increase in Difficulty by one step."
    }
  ],

  alchemy: [
    { name: "Alchemist",
      pre_skills: "alchemy 1 0",  pre_talents: "",
      description: "You may re-roll one d20 when attempting an Alchemy test, but you must accept the new result. With this talent, you can also substitute Alchemy for ranged weapons when using an alchemical weapon."
    },

    { name: "Dabbler",
      pre_skills: "",             pre_talents: "Alchemist 1",
      description: "Having studied many alchemical formulas, you are comfortable with making your own discoveries through experimentation. You are not restricted as to which petty enchantments you would make but doing so is very expensive. You must spend three times the number of reagents needed before making any alchemy test to build a petty enchantment for which you do not have the Master of Formulae talent."
    }

    { name: "Master of Formulae",
      pre_skills: "",             pre_talents: "Alchemist 1;Sorcerer 1",
      description: "Most alchemists work extensively with a specific formula, which becomes second nature. More exacting measures become the standard. When selecting this talent, you must also select a specific type of petty enchantment: blasting powder, lotus pollen, etc. When using this petty enchantment, you may attempt higher Difficulty tests to increase the power of the particular enchantment."
    }

    { name: "Master Alchemist",
      pre_skills: "",             pre_talents: "Master_of_Formulae 1",
      description: "You have refined your measurements to the point of obsession, retesting established formulae, and making unique tools for weighing and separating the resins, fluids, pollens, dusts, and metals of your craft. When working with reagents on any petty enchantment that you have the Master of Formulae talent for, you may roll 1[CD]: if you roll an Effect, you have prevented the waste of much of the reagent. This only counts for one reagent: if multiple reagents are used, the rest are consumed as normal."
    }
  ],

  animal_handling: [
    { name: "Animal Healer",
      pre_skills: "animal_handling 2 0", pre_talents: "Faithful_Companions 1",
      description: "Any time you are called upon to make a Healing test upon an animal, you may instead substitute your Animal Handling skill. You may also substitute your Animal Handling skill for Healing tests upon humans, but you must increase the Difficulty of any such tests by one step."
    },

    { name: "Born in the Saddle",        max_ranks: 3,
      pre_skills: "animal_handling 1 0", pre_talents: "",
      description: "You have spent a lifetime in the company of animals and can recognize personality quirks and identify potential sources of distress. On any Animal Handling test where you generate at least one success, you may immediately roll a number of bonus d20s equal to your ranks of Born in the Saddle. Any successes generated on these additional dice are added to the initial success total, and Complications on these additional dice may be ignored."
    },

    { name: "Charge!",
      pre_skills: "",                    pre_talents: "Born_in_the_Saddle 1",
      description: "You are particularly adept at riding mounts, even those not used to combat. When riding a mount of any kind, the mount is considered combat trained. When riding a horse outside of combat, you can reduce the Difficulty of any tests by one step."
    },

    { name: "Child of Jhebbal Sag",
      pre_skills: "",                    pre_talents: "Voice_of_Jhebbal_Sag 1",
      description: "While not literally one of the offspring of this primitive animal god, your character is nonetheless accepted naturally by animals. Any time you encounter a new animal, you may attempt an Average (D1) Animal Handling test as a Minor Action. On a success, the animal immediately considers you to be a friend. If the target is a guard animal, it does not alert its handlers to your presence."
    },

    { name: "Eyes in the Forest",
      pre_skills: "",                    pre_talents: "Born_in_the_Saddle 1",
      description: "You have come to recognize when animals are reacting to the environment. Any time you are in the company of animals and need to make an Observation test, you may substitute the Animal Handling skill instead, if desired."
    },

    { name: "Faithful Companions",       max_ranks: 3,
      pre_skills: "",                    pre_talents: "Born_in_the_Saddle 1",
      description: "You recognize the needs of your animal companions and are rewarded with devotion. When this talent is purchased, you must nominate a single animal you own. This becomes an animal companion. Generally you can control your companion, though the gamemaster may guide its behavior in some instances. Each additional rank allows you to nominate one additional animal companion. Whenever you succeed at a Survival test to find food, water, or shelter, you automatically find adequate food and shelter for your animal companion(s) as well, without needing to spend Momentum or increase the Difficulty of the task. In addition, when in combat, if you have one or more animal companions within reach, you gain a bonus d20 on your Defend Reactions made against melee and threaten attacks."
    },

    { name: "Voice of Jhebbal Sag",
      pre_skills: "animal_handling 2 0", pre_talents: "Eyes_in_the_Forest 1",
      description: "Wild or tamed matters not to you: all animals are kin and to be afforded due respect. Any time you attempt to direct an animal to take an action that goes against its instinct or training — including instances when the animal is in service of another — any Momentum spent or Doom generated to add bonus d20s to the skill test add two d20s to the dice pool instead of one, though the normal limit of three bonus d20s still applies. In addition, any Momentum spent to obtain information using an Animal Handling test (based on interpreting an animal’s behavior) grants you one additional question. While this is not actual speech, the connection with the animal is uncanny."
    }
  ],

  athletics: [
    { name: "Born Swimmer",                   max_ranks: 3,
      pre_skills: "",                         pre_talents: "Strong_Back 1",
      description: "You are as comfortable in water as you are on land. You can reduce the Difficulty of any swimming test by one step per rank of Born Swimmer, and can ignore any penalties for acting in water."
    },

    { name: "Brutal Brawler",
      pre_skills: "athletics 2 0; melee 0 2", pre_talents: "Pugilist 1",
      description: "You can ignore the effects of the Improvised quality, and increase the damage of the basic Improvised Attack by +1[CD]."
    },

    { name: "Human Spider",
      pre_skills: "",                         pre_talents: "Strong_Back 1",
      description: "You have spent a significant portion of your life in an environment that involves a great deal of climbing, often in the presence of sheer drops. You are very comfortable acting in these environments and never suffer from vertigo or fear of heights. In addition, you never suffer a penalty for a lack of climbing equipment and may reduce the Difficulty of any climbing test by one step."
    },

    { name: "Iron Grasp",
      pre_skills: "",                         pre_talents: "Human_Spider 1;Born_Swimmer 1",
      description: "You never drop or surrender an object unless you wish it. You are immune to the Disarm Momentum spend, and cannot drop your weapon(s) as a result of Complications."
    },

    { name: "Might",                          max_ranks: 3,
      pre_skills: "",                         pre_talents: "Strong_Back 1",
      description: "You are able to perform feats of strength that seem at odds with your physique, due to a combination of training and expertise. On any test to lift or move an inanimate object, you may roll a number of bonus d20s equal to your ranks in Might, though the normal limit of three bonus d20s still applies."
    },

    { name: "Strong Back",                    max_ranks: 3,
      pre_skills: "athletics 1 0",            pre_talents: "",
      description: "You are a magnificent example of human physical prowess, all-too-frequently abused for this ability. For any Athletics test that generates at least one success, you generate one additional success for each rank of Strong Back. Further, your Encumbrance limit is increased by 1 for each rank of Strong Back."
    },

    { name: "Pugilist",
      pre_skills: "athletics 2 0",            pre_talents: "Might 1",
      description: "You can add the Knockdown quality to all melee attacks."
    }
  ],

  command: [
    { name: "Captain",
      pre_skills: "command 1 0",  pre_talents: "",
      description: "You have learned to issue orders in such a way that they are clear to the recipient, with little margin for misinterpretation. You may re-roll one d20 when making a Command test, but you must accept the new result."
    },

    { name: "Commanding Mien",
      pre_skills: "command 2 0",  pre_talents: "Heed_My_Words 1",
      description: "You speak in such a way that even those who do not know you or fully understand your language recognize your charisma and persuasive abilities. You can substitute Command for Linguistics or Persuasion tests."
    },

    { name: "Guardsmen's Eye",
      pre_skills: "",             pre_talents: "Captain 1",
      description: "You are very familiar with the way a crowd would normally act, and recognize actions that are unusual. When dealing with places full of people — even if the people are not organized — you may substitute your Command skill for any Observation or Insight tests that deal with the crowd or the area. You may also use Command to resist against Thievery tests in a crowded area."
    },

    { name: "Heed My Words",
      pre_skills: "",             pre_talents: "Captain 1",
      description: "When attempting to draw the attention of a large group of people, you may pay one Doom point. In return, the targeted characters stop what they are doing and pay attention to your words for the duration of a brief monologue. If used during combat, you may attempt a Command test with a Difficulty equal to the number of non-player characters whose attention you are trying to draw. If the test succeeds, the targeted non-player characters are distracted and may not attempt any actions against you until your next turn. Any other actions attempted by the non-player characters that require a skill test have the Difficulty increased by one step."
    },

    { name: "Inspiring Leader",
      pre_skills: "",             pre_talents: "Captain 1",
      description: "You are an inspiring presence to those who follow you. All of your allies and subordinates gain 2[CD] Morale Soak while they can see or hear you. Any characters who are within close range gain 4[CD] Morale Soak instead."
    },

    { name: "Minions",
      pre_skills: "",             pre_talents: "Commanding_Mien 1",
      description: "Individuals under your authority become extremely loyal to you, perhaps even willing to sacrifice themselves. Any time you come under attack and have a non-player character minion under your command within Reach, that minion may generate one point of Doom. In return, one of your minions also immediately attempts a Protect Reaction. These non-player character minions do not need to be the same, but both must be under your command. "
    },

    { name: "Wise Veteran",
      pre_skills: "command 2 0",  pre_talents: "Guardsmen's_Eye 1",
      description: "You have become proficient in making certain that the actions of a group are well-coordinated. Any time you are involved in a teamwork test — even if you are not the leader for the test — all characters involved may choose to re-roll any die on the initial roll that results in a failure. They must accept the results of the re-roll, even if they are worse than the initial roll."
    }
  ],

  counsel: [
    { name: "An Ear to Listen",
      pre_skills: "",               pre_talents: "Quiet_Wisdom 1",
      description: "You listen patiently to the problems of others, and few can dispute that hearing your voice steadies the nerves and stills doubts. When making a Counsel test to recover Resolve or treat Trauma for another character, every point of Momentum paid or point of Doom generated to add dice to the Counsel test provides two d20s instead of one, though the normal limit of three bonus d20s still applies."
    },

    { name: "Calming Oratory",
      pre_skills: "counsel 2 0",    pre_talents: "An_Ear_to_Listen 1",
      description: "You can speak to people and calm any situation. When making Persuade tests to convince someone to engage in conversation or to avoid violence, you may substitute Counsel for Command, Discipline, or Persuade. If a Struggle emerges from this attempt, the opposing side gains no bonus Momentum for having greater numbers. Once violence has been prevented this talent does not help with further negotiation."
    },

    { name: "Comforting Lies",
      pre_skills: "",               pre_talents: "Quiet_Wisdom 1",
      description: "You know that often, the greatest reassurance comes from denial, and while it is not always the best way to give counsel, it can be valuable in dire times. When you successfully treat one or more Traumas another character has suffered, that character may add 3 points to Doom; the Traumas treated are now healed instead of simply being treated."
    },

    { name: "Motivate",             max_ranks: 3,
      pre_skills: "",               pre_talents: "Comforting_Lies 1",
      description: "You have a way of hastening the recovery of your allies, quickly and effectively restoring their determination and morale. When treating another character to recover their Resolve, you gain 1 bonus Momentum per rank of Motivate, which must be used to recover additional Resolve."
    },

    { name: "Overcome Dark Powers",
      pre_skills: "counsel 3 0",    pre_talents: "Calming_Oratory 1",
      description: "Truly wise counsellors know that while most traumas come from the mortal world, some come from more nefarious sources. When treating Trauma caused by Sorcery or a creature summoned by Sorcery, you may take on some of your patient’s burden. To do this, add 2 points to Doom and suffer a single Trauma. The patient then heals a single Trauma completely. You must heal your newly-gained Trauma as normal."
    },

    { name: "Quiet Wisdom",
      pre_skills: "counsel 1 0",    pre_talents: "",
      description: "You may re-roll any dice that did not generate a success on the initial roll when making a Counsel test, but you must accept the new result."
    },

    { name: "Sophist",
      pre_skills: "",               pre_talents: "Quiet_Wisdom 1",
      description: "You have become known for your wisdom and council, and many are happy to hear you speak. You may substitute Counsel for Persuade or Society."
    }
  ],

  craft: [
    { name: "Armorsmith",
      pre_skills: "",           pre_talents: "Journeyman 1",
      description: "You have the knack for repairing armor in the field; making do with whatever is available to repair your armor and that of your allies, even when resources are scarce. When repairing armor away from proper tools and materials, you may add 2 points to Doom in order to attempt a repair on a single hit location’s armor, without the use of materials."
    },

    { name: "Barricade",
      pre_skills: "",           pre_talents: "Armorsmith 1",
      description: "You have learnt to put up barricades or small structures quickly and efficiently. If you take a Standard Action to create a barricade, you can find or create light cover enough for one character. If given suitable time, you can find or create protections for an entire zone."
    },

    { name: "Journeyman",
      pre_skills: "craft 1 0",  pre_talents: "",
      description: "You have passed apprenticeship and passed its trials. When making a Craft test, you may either roll one extra d20 or spend 1 Doom to reduce the Difficulty of the test by one step, to a minimum of 0."
    },

    { name: "Labor of Love",
      pre_skills: "",           pre_talents: "Master_Smith 1",
      description: "Master Smiths can create truly beautiful works. When you have access to your tools and create a labor of love, you can use any bonus Momentum granted by Master Smith to increase the attractiveness of your work. This offers little functional difference to the finished item itself, but will increase your wealth and influence. With Labor of Love, you can use Craft in place of Society tests and gain 1 extra level of Renown for every rank of Master Smith."
    },

    { name: "Mason",
      pre_skills: "craft 2 0",  pre_talents: "Barricade 1",
      description: "You have been apprenticed to a skilled mason, and have learned the specialised and highly-valued skills necessary to oversee the construction of important buildings: temples, castles, palaces, and similar monuments. When overseeing a team of laborers during a construction project, you may use your Craft skill instead of Command. With a Standard Action, you can find or create heavy cover adequate for one character. Given suitable time and resources, you can create this level of protection for an entire zone."
    },

    { name: "Master Smith",     max_ranks: 3,
      pre_skills: "craft 2 0",  pre_talents: "Journeyman 1",
      description: "You work faster than lesser workers and have the vision to recognize alternative uses of common items. With success on a Challenging (D2) Craft test, you can adapt existing items at hand in order to solve a problem. This adaptation is only good for a single use. Any Momentum from the test can be spent to provide an additional use, 1 extra per point of Momentum. After the final use has been completed, the item is ruined for both the alternative use and its originally intended use.\nWhen you have access to your tools you gain bonus Momentum equal to your ranks in Master Smith, which may only be spent on reducing the time taken to complete the task."
    },

    { name: "Sabotage!",
      pre_skills: "",           pre_talents: "Journeyman 1",
      description: "You are able to identify the problem with any broken item or structure, or to recognize a vulnerability that could be used to cause such a break. You reduce by one the Difficulty of any Craft test to perform repairs or maintenance. When an Exploit Action is taken using the Craft skill, Sabotage! grants bonus Momentum equal to your Craft Skill Focus."
    }
  ],

  discipline: [
    { name: "Blessed",
      pre_skills: "discipline 2 0", pre_talents: "Healthy_Superstition 1",
      description: "You are particularly resistant to supernatural attempts to manipulate your perceptions, beliefs, and mental processes. Any time you attempt to resist supernatural powers that target your mind, you may re-roll any d20s that did not generate at least one success, though the second roll stands. Further, each d20 that you roll a 1 on will cause a single Complication for the attacker."
    },

    { name: "Courageous",
      pre_skills: "discipline 1 0", pre_talents: "",
      description: "You may re-roll a single d20 on any Discipline test, though the second result stands. For every point of Discipline Focus, you gain 1 Courage Soak."
    },

    { name: "Healthy Superstition",
      pre_skills: "",               pre_talents: "Courageous 1",
      description: "Some superstitions are just common sense, and you hold many of those beliefs. This superstition allows you to stand firm in the face of the unnatural, even if doing so would seem foolhardy. When facing supernatural threats, you are empowered by this belief. When a supernatural threat manifests, you may spend one Momentum (Immediate, Repeatable) to immediately gain 1[CD] Morale Soak, which lasts until the end of the current scene."
    },

    { name: "Iron Will",
      pre_skills: "",               pre_talents: "Courageous 1",
      description: "You have survived countless challenges and are prepared to face even more. You don’t cry out when struck or startled, and you quickly rebound from Stress. Rather than having to choose a particular stress when you take a Recover Action, you recover both Vigor and Resolve, regaining the same amount of each (two points, plus two per Momentum spent). In addition to this you can add 2 points to Doom in order to perform the Recover Action as a Minor Action. If you use this option, you do not get to re-roll Cover dice, as outlined in the Recover Action."
    },

    { name: "Jaded",                max_ranks: 3,
      pre_skills: "",               pre_talents: "Courageous 1",
      description: "You have repeatedly observed and suffered cruelties, and have built up a tolerance to mental suffering. Increase your maximum Resolve by one for each rank of Jaded."
    },

    { name: "Wary", max_ranks: ,
      pre_skills: "",               pre_talents: "Jaded 1",
      description: "You have seen countless attempts at manipulation, and no longer trust easily. Whenever you are the target of a Persuade or Command action by another character or non-player character, any Momentum spent (or points added to Doom) to add bonus d20s to the Willpower test adds two dice instead of one, though the normal limit of three bonus d20s still applies. Further, if you resist the manipulation attempt, any other characters who have been convinced may each spend 1 Momentum (Immediate) to see through the manipulation, inspired by your example."
    }
  ],

  healing: [
    { name: "A Little to Ease the Pain",
      pre_skills: "",               pre_talents: "Bind_Wounds 1",
      description: "In your past you worked with extremely limited resources, and have learned to take full advantage of them when available. When using medicine from a healer’s bag, each load adds two d20s to the Healing test, instead of the usual one, though the normal limit of three bonus d20s still applies. In addition, if you have access to narcotics or alcohol you can make a Daunting (D3) Healing test to convert a dose of either into a dose of medicine."
    },

    { name: "Anatomist",
      pre_skills: "",               pre_talents: "This_Will_Hurt 1",
      description: "You know the human body like no other and can exploit this in many ways. When making a Healing test to treat injuries, you can reduce the Difficulty of any test by one step, to a minimum of Average (D1). In addition to this you may add +1[CD] and the Vicious 1 quality to any melee or Threaten attack you make, as your knowledge of the body makes your cuts and your threats alike all-the-crueller and more specific. "
    },

    { name: "Apothecary",
      pre_skills: "",               pre_talents: "A_Little_to_Ease_the_Pain 1",
      description: "You are well-versed in treating poisons. You can attempt an Average (D1) Healer test any time you encounter a poisoned or drugged patient. On success, you are able to identify both the poison or drug and the antidote necessary to relieve its symptoms. You may spend Momentum to have the antidote at hand, though the amount required is subject to the gamemaster’s discretion, based upon the rarity and toxicity of the poison or drug. You can use the Healing skill instead of Alchemy or Animal Handling when treating or procuring venoms."
    },

    { name: "Avoid Danger",
      pre_skills: "",               pre_talents: "Bind_Wounds 1",
      description: "You recognize various environmental risks and know how to mitigate them. You may substitute your Healing skill for Survival for the purposes of avoiding hazards."
    },

    { name: "Bind Wounds",
      pre_skills: "healing 1 0",    pre_talents: "",
      description: "You may re-roll one d20 when using the Healing skill, but you must accept the new result."
    },

    { name: "Chirurgeon",
      pre_skills: "healing 2 0",    pre_talents: "Apothecary 1",
      description: "You have encountered a variety of sicknesses, plagues and injuries, and have learned many effective ways of treating these maladies. You can attempt an Average (D1) Healing test to identify the best course of treatments for any patient you encounter. On a success, you are able to prescribe a suitable remedy. You may spend Momentum to have the necessary treatments on hand, though the cost in both money and time is subject to the gamemaster’s discretion. You are a figure of authority and can substitute Healer for the Command skill. If you command another character to assist you or to act in your stead, that character can reroll a single d20 of their own Healing test. Given suitable downtime, you can completely heal the injuries of others."
    },

    { name: "This Will Hurt",
      pre_skills: "",               pre_talents: "Bind_Wounds 1",
      description: "You know that setting bones and tending to injuries will cause plenty of pain, and there’s little good that comes from being gentle when trying to save a life. Better that they suffer pain now and live to tell of it. When you attempt to treat a patient’s injuries, you may choose to reduce the Difficulty of the test by up to three steps. However, if you do this, you also inflict 2[CD] mental damage on that patient, plus an additional +1[CD] for every step of Difficulty reduced, as your swift and indelicate actions cause the patient intense pain."
    }
  ],

  insight: [
    { name: "Know the Signs",
      pre_skills: "",               pre_talents: "Pierce_the_Veil 1",
      description: "You have personally dealt with the effects of the supernatural, and recognize the signs of its activity. Whenever you are in the presence of a person or object that was affected by supernatural abilities within the last six hours, you may attempt an Insight test, with a Difficulty equal to the number of hours ago the person or object was affected. On success, you can recognize the taint of the supernatural. By spending 2 points of Momentum, you can identify the specific powers in use."
    },

    { name: "Pierce the Veil",
      pre_skills: "",               pre_talents: "Sixth_Sense 1",
      description: "You have a knack for recognizing the subtle cues of supernatural ability. Whenever you are in the presence of the supernatural or beings with unusual powers — particularly if you are not aware of them — the gamemaster should call for you to attempt an Average (D1) Insight test. On success, you recognize that the other being (or presence) has supernatural abilities, and may spend 2 Momentum to identify the type of abilities. This test should be made even if the target does not have any active abilities."
    },

    { name: "Rescue the Innocents",
      pre_skills: "",               pre_talents: "Witch 1",
      description: "Instead of using the ability from Witch, prior to combat you can attempt a Simple (D0) Insight test to evacuate innocents from the scene. For every Momentum spent, you can earmark three chosen non-player characters and ensure that they get to safety. These non-player characters cannot be targeted by combat unless the gamemaster pays three points of Doom for each attack."
    },

    { name: "See the Soul",
      pre_skills: "",               pre_talents: "Sixth Sense 1",
      description: "While you might not literally see the human soul, you can intuitively relate your alternate senses to the physical world. When dealing with mortal humans you may substitute your Insight skill for Observation, Social, Stealth, or Thievery."
    },

    { name: "Sixth Sense",
      pre_skills: "insight 1 0",    pre_talents: "",
      description: "You may re-roll one d20 when making an Insight test, but you must accept the new result. In the event of an ambush, you gain 1 additional bonus point of Momentum. If the Insight test was requested because of sorcerous or otherwise unnatural phenomena, the gamemaster must reveal this."
    },

    { name: "Smell Out Sorcery",
      pre_skills: "",               pre_talents: "Rescue_the_Innocents 1;Sorcerer 1",
      description: "Instead of using the ability from Witch prior to combat, you can attempt a Challenging (D2) Insight test to sense any sorcery, whether a sorcerer, summoned creature, ruin or artifact within medium range. However, this test is highly inaccurate and its consequences may target innocent victims."
    },

    { name: "Witch", max_ranks: 3,
      pre_skills: "",               pre_talents: "Sixth_Sense 1",
      description: "Whether from dire sorcery or human cruelty, you have learned to discover when matters will escalate. Prior to any combat, you can attempt a Dire (D4) Insight test to gain an additional Standard Action. This Action takes place as if you had spent a Fortune point. Each additional rank of this talent beyond the first reduces the Insight test by one Difficulty step."
    }
  ],

  linguistics: [
    { name: "Accent",
      pre_skills: "",                 pre_talents: "Traveler's_Tongue 1",
      description: "You are familiar with the idioms and speech patterns of a broad range of different populations. You know not just how to speak a language, but how to speak it in a fashion that sets a native speaker at ease, often even utilizing a local dialect. You can substitute Linguistics for Persuade."
    },

    { name: "A Cryptic Ear",
      pre_skills: "",                 pre_talents: "Traveler's_Tongue 1",
      description: "You have a knack for spotting and solving word and number ciphers, even those hidden in plain sight. So long as you are fluent in the language spoken, the Difficulty of any test to decipher the hidden meaning is reduced by one step. In addition, you can add 1 to Doom in order to reduce the Difficulty of the test by one step further. This may eliminate the need for a test, if it becomes lower than Simple (D0)."
    },

    { name: "Body Language",
      pre_skills: "",                 pre_talents: "Polyglot 1",
      description: "You are a master at understanding people. You can speak with any living person so long as there is no immediate distraction that would prevent communication, at which point the Linguistics skill must be used as normal. This communication requires a Standard Action but no test is needed. You can also substitute Linguistics for Insight."
    },

    { name: "Polyglot",
      pre_skills: "linguistics 0 2",  pre_talents: "Accent 1",
      description: "You are a master at understanding languages. You speak the active languages of all the locations you have traveled to, and will immediately learn the active languages of anywhere you visit. Learning the language(s) costs 1 Fortune point, which can be spent at any time during the visit."
    },

    { name: "Translator",
      pre_skills: "",                 pre_talents: "Traveler's_Tongue 1",
      description: "You can read more languages than you can speak. For every Linguistics talent possessed, you can add one language that you can read with fluency. You do not count as fluent when hearing or speaking the language, though you can still communicate fluently through writing should you find a literate character to converse with."
    },

    { name: "Traveler's Tongue",
      pre_skills: "linguistics 1 0",  pre_talents: "",
      description: "You gain one additional language fluency for every Linguistics talent you possess."
    },

    { name: "Two Tongues",
      pre_skills: "linguistics 0 2",  pre_talents: "A_Cryptic_Ear 1",
      description: "You are a master at expression and can transmit a private message at the same time as a public one. You can take two Speak Actions at the same time. For others, cracking your spoken code is a Daunting (D3) Linguistics test, though for the expected recipient it is an Average (D1) Linguistics test to understand the message."
    }
  ],

  lore: [
    { name: "Common Ground",
      pre_skills: "",           pre_talents: "Scribe 1",
      description: "You have a broad education that includes an understanding of history and culture from a variety of different perspectives. When interacting with an opponent, you may attempt an Average (D1) Lore test as a Minor Action. On success, you recognize within your opponent an element of common ground for discussion. Any Momentum from the Lore test may be immediately added to a Persuade or Command test, taken as a Standard Action."
    },

    { name: "The Enemy of My Enemy",
      pre_skills: "",           pre_talents: "Know_Your_Enemy 1",
      description: "You have come to recognize the reasons why an opponent is acting in a particular way, and can use that to dissuade them from acting. You may substitute your Lore skill for Command, Counsel, or Persuade when making a test against an opponent whose motivations you understand."
    },

    { name: "Know Your Enemy",
      pre_skills: "lore 2 0",   pre_talents: "Politically_Savvy 1",
      description: "When analyzing an opponent’s pattern of actions — including combats, social interactions, and rumors — you have learned to recognize your foe’s overall strategy. Once you have assembled the available clues, you may spend 1 Doom point. The gamemaster must then truthfully reveal your opponent’s short-term goals."
    },

    { name: "Play the Part",
      pre_skills: "lore 2 0",   pre_talents: "Common_Ground 1",
      description: "You are so familiar with foreign cultures that you have learned to impersonate the members of a broad range of cultures. This includes style of dress, speech, and other mannerisms. When attempting to make use of a disguise, you may substitute your Lore skill for Stealth."
    },

    { name: "Politically Savvy",
      pre_skills: "",           pre_talents: "Scribe 1",
      description: "You are familiar with the philosophies, styles, and motivations of various political entities. When interacting with an opponent, you may attempt a Simple (D0) Lore test as a Minor Action. One Momentum is enough to recognize the foe’s significant political and personal affiliations, based upon their apparent mannerisms and actions. Additional Momentum provides more detailed information."
    },

    { name: "Sage", max_ranks: 3,
      pre_skills: "",           pre_talents: "Scribe 1",
      description: "You have an impressive amount of knowledge at an academic level. When performing research on any topic covered by the Lore skill you may reduce the Difficulty by one step per rank of Sage. This may eliminate the need for the test. "
    },

    { name: "Scribe",
      pre_skills: "lore 1 0",   pre_talents: "",
      description: "You have had access to at least a small library of books, scrolls, or tablets, and gained a fascination with learning and knowledge. When rolling a Lore test you gain one bonus Momentum for every d20 that rolls less than your Lore Focus. This bonus Momentum can only be used for the Obtain Information Momentum spend."
    }
  ],

  melee: [
    { name: "Adaptable Combatant",
      pre_skills: "melee 3 0",      pre_talents: "Deft_Blade 1",
      description: "You can adjust your fighting style to suit a range of circumstances. When making or defending against an attack, you may increase or decrease the Reach of your weapon by 1. A weapon’s Reach may not be reduced below 1"
    },

    { name: "Blood on Steel",
      pre_skills: "melee 2 0",      pre_talents: "No_Mercy 1",
      description: "You do not hesitate to bloody your weapons. When rolling for damage with a melee attack, you may spend one Momentum in order to add the Vicious 1 quality to the weapon, or increase the weapon’s Vicious quality by 1 if it already possesses the quality."
    },

    { name: "Deft Blade",
      pre_skills: "melee 2 0",      pre_talents: "No_Mercy 1",
      description: "You wield a blade as if it were an extension of your arm. Whenever you make a melee attack, any Momentum spent or points added to Doom to add bonus d20s to the Melee test adds two dice instead of one, though the normal limit of three bonus d20s still applies."
    },

    { name: "Grappler",
      pre_skills: "",               pre_talents: "No_Mercy 1",
      description: "You know that a mobile foe is a dangerous one, and the easiest way to stop someone moving is to grab hold of them. After making a successful melee attack, you may spend 1 Momentum to gain the Grappling quality on an unarmed attack."
    },

    { name: "Killing Strike",
      pre_skills: "melee 3 0",      pre_talents: "Blood_on_Steel 1",
      description: "Your strikes are deadly, making corpses of all who cross you. When you inflict 1 or more Wounds as a result of a melee attack, you may spend 2 Momentum in order to inflict an additional Wound immediately. Against a mob or squad of enemies, this additional Wound may be applied to another member of that mob or squad."
    },

    { name: "Murder in the Eyes",
      pre_skills: "",               pre_talents: "Grappler 1",
      description: "You are a savage up close, where your foes can feel the wet heat of your breath and see the savagery in your gaze. When attacking an opponent that does not have Guard, add +2[CD] to your damage roll."
    },

    { name: "No Mercy",
      pre_skills: "melee 1 0",      pre_talents: "",
      description: "When making a Melee attack, you may re-roll a number of damage dice equal to the total number of Melee talents (and ranks in those talents) you have acquired, if desired. You must accept the results of the re-rolls."
    }
  ],

  observation: [
    { name: "Battlefield Perception",
      pre_skills: "obeservation 2 0", pre_talents: "Scout 1",
      description: "During combat, you may choose one enemy and make an Average (D1) Observation test as a Minor Action. If successful, you can determine how much of the target’s Stress remains, and how many Harms the target is suffering from. For one Momentum (Repeatable), you may choose one additional foe."
    },

    { name: "Crippling Blow",
      pre_skills: "",                 pre_talents: "Battlefield_Perception 1",
      description: "You know how to place your blows to deal crippling harm. After making a successful attack, you may add 1 point to Doom in order to make the attack particularly effective. Add a number of additional damage dice to the attack equal to your Observation Focus. Each time this ability is used in a single scene, the cost of using the ability increases by 1: the first time adds 1 to Doom, the second adds 2, the third adds 3, etc."
    },

    { name: "Perfect Memory",
      pre_skills: "",                 pre_talents: "Sharp_Senses 1",
      description: "You have a knack for recalling information, even if it was irrelevant at the time. You can make an Observation test to investigate any area you’ve been to, even if you are not in that location any more. You cannot change any of the physical features of the area, meaning that your memory is limited to what you actually experienced. For example, if you didn’t look behind a tapestry or open a door, you have no idea what they conceal. However, if you also have the Ransack talent, it should be assumed that you opened/closed all doors and looked at the scene from multiple points of view."
    },

    { name: "Ransack",
      pre_skills: "",                 pre_talents: "Sharp_Senses 1",
      description: "You are adept at thoroughly searching an area quickly. The search is obvious to any onlookers and any who examine the area searched, with a Difficulty determined by the size of the area to be searched. Searching within Reach requires an Average (D1) Observation test, while searching within Close range becomes a Challenging (D2) test. With a successful Observation test, you identify all of the clues that you currently consider important in that area. Ransack takes a Standard Action and can be attempted multiple times."
    },

    { name: "Scout",
      pre_skills: "",                 pre_talents: "Sharp_Senses 1",
      description: "You can survey a new environment quickly. The first time you attempt an Observation test in a location you’ve never been before, you gain 1 bonus Momentum, which must be used on the Obtain Information Momentum spend."
    },

    { name: "Sharp Senses",
      pre_skills: "obeservation 1 0", pre_talents: "",
      description: "You may re-roll one d20 when making an Observation test, but you must accept the new result."
    },

    { name: "Spy",
      pre_skills: "obeservation 2 0", pre_talents: "Ransack 1",
      description: "You can perform the Ransack talent without leaving tell-tale evidence of the search. To notice that a search has been undertaken, you must engage in a Struggle with the character that used this talent upon the space, gaining bonus Momentum equal to your Observation Focus."
    }
  ],

  parry: [
    { name: "Crowd Pleaser",
      pre_skills: "",           pre_talents: "Stage_Fighting 1",
      description: "You have become adept at gauging your attacks to create more spectacular results that are less lethal than they appear. After successfully hitting with a Melee attack, but before rolling for damage, you can reduce the damage of the attack by up to 3[CD]. You gain 1 bonus Momentum for each [CD] of damage reduced."
    },

    { name: "Deflection",
      pre_skills: "parry 1 0",  pre_talents: "",
      description: "You know the importance of keeping your weapons up and ready to defend. When making a Defend Reaction using the Parry skill, you can reduce the number of points added to Doom by 1, to a minimum of 0. This stacks with the weapon’s Parrying quality."
    },

    { name: "Reflexive Block",
      pre_skills: "",           pre_talents: "Riposte 1",
      description: "You have become so attuned to your Parry skill that you may use your Parry skill when attempting a Defend Reaction against a ranged attack, which is normally not possible."
    },

    { name: "Riposte",
      pre_skills: "",           pre_talents: "Deflection 1",
      description: "The instant after an attack is the moment when the attacker is the most vulnerable. After successfully making a Defend Reaction using the Parry skill, you may immediately add 1 to Doom in order to make a Melee attack against the foe you just parried. Momentum remaining from the Parry Action may be carried over to this Melee attack."
    },

    { name: "Stage Fighting",
      pre_skills: "",           pre_talents: "Deflection 1",
      description: "You can believably fake combat with others, presenting no risk to the ones facing you. When using Parry to engage in such deception, any attack made gains the Nonlethal quality."
    },

    { name: "Tutored Warrior",
      pre_skills: "",           pre_talents: "Deflection 1",
      description: "You can study human foes to learn their weaknesses, drawing them out in combat to see how they react, and thus, learning how to exploit those moments when they are unintentionally defenseless. As a Standard Action, you may attempt a Daunting (D3) Parry test to learn one particular enemy’s patterns and weaknesses. For the remainder of the scene, you may re-roll a single d20 on every Melee or Parry skill test made against that enemy."
    }
  ],

  persuade: [
    { name: "Force of Presence",  max_ranks: ,
      pre_skills: "",             pre_talents: "",
      description: "Your damage bonus on mental attacks is increased by +1[CD]."
    },

    { name: "Haggler",
      pre_skills: "persuade 2 0", pre_talents: "Force_of_Presence 1",
      description: "You are particularly proficient at striking a bargain, either to obtain goods or favours. After making a Society test to purchase an item, you may roll a Simple (D0) Persuade test and reduce the cost by 1 by spending 2 Momentum (Repeatable)."
    },

    { name: "Naturally Charming", max_ranks: 3,
      pre_skills: "",             pre_talents: "Force_of_Presence 1",
      description: "You have a warm personality and a winning smile. People trust you. A successful Persuade test yields 1 point of bonus Momentum per rank of Naturally Charming."
    },

    { name: "Remorseless",        max_ranks: 3,
      pre_skills: "",             pre_talents: "Haggler 1",
      description: "You are willing and able to tell any lie that you feel is necessary to overcome an opponent’s social defenses. When lying to an opponent, you gain one additional d20 per rank of Remorseless to your Persuade or Command test."
    },

    { name: "Seducer",
      pre_skills: "",             pre_talents: "Naturally_Charming 1",
      description: "You are particularly adept at seducing others. When attempting a seduction, you gain two additional d20s to your Persuade test per Momentum spent or Doom generated, instead of one, though the normal limit of three additional d20s still applies."
    },

    { name: "Social Chameleon",
      pre_skills: "",             pre_talents: "Remorseless 1",
      description: "It is one thing to be convincing for a minute, it is another to be convincing for a lifetime. When impersonating a different social caste, this talent lets you substitute your Persuade skill in place of Animal Handling, Craft, Insight, Society, Survival, or Thievery, though only when convincing others that you have this expertise. Any practical application of the skill that requires actual knowledge relies on your existing relevant skill, if any."
    },

    { name: "Strong-Arm Tactics", max_ranks: 3,
      pre_skills: "",             pre_talents: "Force_of_Presence 1",
      description: "You recognize others’ limitations and can easily exploit them. When attempting to intimidate an opponent, you are able to recognize the most effective strategies to use. You gain one additional d20 to any Persuade or Command test per rank of Strong-arm Tactics. Further, you gain Piercing X on your Threaten attacks, where X is equal to your ranks in Strong-arm Tactics."
    }
  ],

  ranged: [
    { name: "Accurate",
      pre_skills: "ranged 1 0",       pre_talents: "",
      description: "When making an attack with a ranged weapon, you may re-roll a number of damage dice equal to the number of Ranged Weapon talents (and ranks in those talents) you have acquired. You must accept the result of these re-rolls."
    },

    { name: "Blot Out the Sun",
      pre_skills: "",                 pre_talents: "Hail_of_Arrows 1",
      description: "When you target a mob or gang with a ranged attack, you can reduce the cost of the Hail of Arrows Momentum spend to 1."
    },

    { name: "Hail of Arrows",
      pre_skills: "",                 pre_talents: "Quick_Release 1",
      description: "When you attempt a ranged attack with a weapon with the Volley quality and spend one or more Loads, you may spend 2 Momentum to add the Area quality to the attack."
    },

    { name: "Marksman",               max_ranks: 3,
      pre_skills: "",                 pre_talents: "Accurate 1",
      description: "You have learned to perform ranged attacks with great precision. You may spend a Minor Action before attempting a ranged attack, putting a little more time and effort into your attack. When you do this, you gain 1 additional Momentum per rank of Marksman to use for the attack."
    },

    { name: "Quick Release",
      pre_skills: "ranged 2 0",       pre_talents: "Accurate 1",
      description: "You are able to ready a shot almost as soon as you’ve loosed the previous one. When using a ranged weapon with the Volley quality, you may spend a Minor Action to increase your rate of attack, allowing you to spend two Loads, gaining a bonus d20 and +1[CD] damage for each Load spent."
    },

    { name: "Shoot for the Horizon",
      pre_skills: "",                 pre_talents: "Accurate 1",
      description: "You have learned to take shots at any range compensating instinctively for variations in weapon manufacturing, weather conditions, and other anomalies that could affect the trajectory of an attack. You can reduce the penalty for firing at a range other than the weapon’s optimal range by one step, to a minimum of 0."
    },

    { name: "Trick Shot",             max_ranks: 3,
      pre_skills: "ranged 0 3",       pre_talents: "Shoot_for_the_Horizon 1",
      description: "You are an extremely precise shot. You gain bonus Momentum on ranged attacks equal to your rank in this talent, though these may not be used to increase the attack’s damage and may not be saved in the group pool."
    }
  ],

  resistance: [
    { name: "Hardy",
      pre_skills: "resistance 1 0", pre_talents: "",
      description: "When making a Resistance test, you may re-roll any dice that did not generate a success on the initial roll, but you must accept the new result."
    },

    { name: "Impervious",
      pre_skills: "resistance 2 0", pre_talents: "Just_a_Scratch 1",
      description: "You have been injured before, and have faced something more grievous than what just happened to you. When you suffer a Wound, you may pay 1 Fortune point to ignore that Wound entirely."
    },

    { name: "Indefatigable",
      pre_skills: "resistance 1 0", pre_talents: "Hardy 1",
      description: "You are tireless, able to press on when others would falter. Whenever you would suffer Fatigue, you may ignore it by adding a number of points to Doom equal to the Fatigue suffered."
    },

    { name: "Iron-Skinned",
      pre_skills: "",               pre_talents: "Impervious 1",
      description: "You are so used to taking injuries that it now takes an impressive amount of damage to actually hurt you. You increase your Armor Soak on all locations by 1, and you still benefit from this Armor Soak if you are not wearing armor on that location (even if the armor was sacrificed)."
    },

    { name: "Just a Scratch",       max_ranks: 2,
      pre_skills: "",               pre_talents: "Hardy 1",
      description: "You have a knack for shrugging off injuries that would fell a lesser mortal. The amount of physical damage needed to inflict a Wound is increased by 1 per rank of Just a Scratch. For example, if you have Just a Scratch 1, you will suffer a Wound if 6 or more points of damage are inflicted, rather than the normal total of 5 or more."
    },

    { name: "Resilient",            max_ranks: 3,
      pre_skills: "",               pre_talents: "Stubborn_as_a_Mule 1",
      description: "Your physique is particularly sturdy and resilient. Whenever you suffer a condition that may be avoided by adding to Doom, you can reduce the amount of Doom you need to pay by your rank in Resilient, to a minimum of 0."
    },

    { name: "Stubborn as a Mule",
      pre_skills: "",               pre_talents: "Hardy 1",
      description: "You have gone through grievous injuries and survived truly epic quantities of ale and mead. You have learned how to face down the seemingly insurmountable, and rely on your physical stamina to do so. When already suffering from an injury, you may substitute your Resistance skill for Discipline, if desired."
    }
  ],

  sailing: [
    { name: "Alone at Sea",
      pre_skills: "",             pre_talents: "Sea_Legs 1",
      description: "When a ship is damaged on the water, it is often unable to reach a port where repairs can be made, requiring a temporary solution. You are familiar with the methods of repairing a ship in the short-term so that it can survive long enough to undergo proper repairs. You may substitute your Sailing skill for Craft when attempting repairs on watercraft. However, those repairs will only last for a scene, plus an additional Scene per Momentum (Repeatable), before proper repairs are required."
    },

    { name: "Catch the Wind",     max_ranks: 3,
      pre_skills: "sailing 2 0",  pre_talents: "Navigation 1",
      description: "You know the nuances of sailing, and can guide a vessel safely through difficult and dangerous situations. Decrease the Difficulty for any Sailing tests by one step per rank of Catch the Wind when you are piloting."
    },

    { name: "Navigation",
      pre_skills: "",             pre_talents: "Sailor 1",
      description: "You have learned to navigate watercraft through the many hazards of the sea. You may ignore any penalties to the Difficulty of a Sailing test incurred by situational hazards, including harsh weather, magical impediments, and similar dangers."
    },

    { name: "Old Salt",
      pre_skills: "sailing 2 0",  pre_talents: "Alone_at_Sea 1",
      description: "You are a veteran ship-hand: you’ve weathered storms, survived pirates, and struggled through the foulest misfortune. Through all of it, you’ve learned to trust your own skills and those of your shipmates, and learned to spot the wide range of expertise available on a ship’s crew. While onboard a ship with a reasonably-sized crew, you may add 1 to Doom in order to substitute your Sailing skill for any skill, except for Alchemy or Sorcery."
    },

    { name: "Sailor",
      pre_skills: "sailing 1 0",  pre_talents: "",
      description: "You are an experienced sailor, accustomed to river, sea, or ocean. You may re-roll one d20 when making a Sailing test, but you must accept the new result."
    },

    { name: "Sea Legs",
      pre_skills: "",             pre_talents: "Sailor 1",
      description: "You have been at sea for a long time, and are more-than-familiar with the swaying and shifting of the deck, so much so that you may even be a little out of sorts when on dry land. You no longer suffer any penalties caused by the random motion of being aboard a ship when taking any test. Additionally, you may substitute Sailing for Acrobatics, Athletics, or Resistance while onboard a ship or when using a rope."
    },

    { name: "Seafarer",
      pre_skills: "",             pre_talents: "Sailor 1",
      description: "You are a reputable sailor with a name known in many ports. You can add 1 to Doom in any port to find someone who will vouch for you, including ports you have not yet travelled to. For the duration of the stay, this allows you to substitute Sailing for Society and grants a bonus d20 on any tests using Sailing in place of Society. If you are asked for a favor by another sailor at any time during your stay, you must grant it, or the effects of Seafarer can no longer be used for that stay."
    }
  ],

  siegecraft: [
    { name: "Artillerist",
      pre_skills: "siegecraft 1 0", pre_talents: "Strategist 1",
      description: "You have learned how best to operate siege weaponry. When making an attack with a siege weapon, you may re-roll a number of damage dice equal to the number of Siegecraft talents (and ranks in them) you have acquired. The results of these re-rolls must be accepted."
    },

    { name: "Ballistics",           max_ranks: 3,
      pre_skills: "",               pre_talents: "Artillerist 1",
      description: "You have experience firing large and inaccurate weapons over long distances, and have learned the techniques that make these weapons truly effective. For each rank of Ballistics, you can reduce the Difficulty of a Siegecraft test to attack with a siege weapon by one step, to a minimum of Average (D1). Each rank of Ballistics also increases the damage of a siege weapon used by +1[CD]."
    },

    { name: "Conqueror",
      pre_skills: "siegecraft 2 0", pre_talents: "General 1",
      description: "With this talent, you have learned how to bring your retinue (generated with the General talent, below) to bear with explosive force; any warrior in your retinue adds a bonus d20 to all Melee, Parry, Ranged Weapons, and Siegecraft tests. Warriors in your retinue no longer need to be within earshot to gain the benefit of your leadership. As with the General talent, this benefit does not apply to other player characters, even if they are under your control. "
    },

    { name: "Devastating Bombardment",
      pre_skills: "siegecraft 2 0", pre_talents: "Ballistics 1",
      description: "You have learned how to get the greatest effect from siege weaponry, using shots to shatter morale as well as masonry. After making a successful attack with a siege weapon, you may spend 2 points of Momentum to unleash a Devastating Bombardment. A Devastating Bombardment forces all creatures within Close range of the attack’s target to attempt an Average (D1) Discipline test or suffer mental damage equal to the attack’s damage rolled. Additionally, any Momentum spent to add damage to the Devastating Bombardment adds 2 points of damage rather than 1."
    },

    { name: "General",              max_ranks: 3,
      pre_skills: "",               pre_talents: "Strategist 1",
      description: "You have become particularly adept at coordinating the actions of soldiers. When leading an army or unit of warriors in battle you can substitute Siegecraft for Command, Counsel, or Persuade. In addition, you can create a retinue (warband, squad, etc.) of dedicated and highly-loyal warriors of a size equal in number to your Siegecraft Focus times your rank in this talent. For example, if you have General 2 and Siegecraft Focus 2, you can have up to four warriors in your retinue. The warriors in your retinue must be chosen prior to combat, must be dedicated followers who have trained with you, and must be within earshot to gain any benefits. This benefit does not apply to other player characters, even if they are under your control. These are considered to be Elite Minions, whereas normal soldiers or warriors are normal Minions."
    },

    { name: "Spotter",
      pre_skills: "",               pre_talents: "Strategist 1",
      description: "You are familiar with discovering enemy positions and communicating this back to your leader. When assisting in setting up or seeking out an ambush, or when assisting an artillery crew as a spotter, you may add your Siegecraft dice pool rather than only a single d20."
    },

    { name: "Strategist",
      pre_skills: "siegecraft 1 0", pre_talents: "",
      description: "You are an experienced soldier that has fought in significant battles, skilled in assaulting and defending buildings. When crossing an obstacle or hindering terrain, or while skirting a hazard, you gain the benefit of Light Cover (2[CD] Cover Soak) from any ranged weapon attack, including siege weapons."
    }
  ],

  society: [
    { name: "A Modicum of Comfort",
      pre_skills: "society 1 0", pre_talents: "",
      description: "You have a legacy of wealth or substantial funds available to you, and can leverage old debts into sustaining you. Reduce your Upkeep by 1, to a minimum of 1."
    },

    { name: "Ear of the King",
      pre_skills: "", pre_talents: "Wealthy 3; Reputation 2",
      description: "You know the best way to raise awareness of an issue with the proper authorities. When attempting to spread a message across a large group of people, or even a region, you can substitute your Society skill for Command. In addition, the Difficulty for all skill tests dealing with civic figures is reduced by one step, so a minimum of Simple (D0)."
    },

    { name: "Friends in the Maul",
      pre_skills: "society 2 0", pre_talents: "Garrulous 1",
      description: "Once you have lived in any place for any length of time you pick up a variety of hangers-on and informants. In any location where you have had downtime, you have at least one useful contact on tap. All skill tests made during downtime gain a d20 so long as the skill test does not involve combat of any kind."
    },

    { name: "Garrulous", max_ranks: 3,
      pre_skills: "", pre_talents: "A_Modicum_of_Comfort 1",
      description: "You have an ever-expanding range of transitory contacts. Any time you need assistance from other individuals, you may reduce the Difficulty to find a contact by one step per rank of Garrulous."
    },

    { name: "Powerful Friends",
      pre_skills: "", pre_talents: "Friends_in_the_Maul 1",
      description: "You know many powerful people in positions of significant authority. When selecting this talent, you gain a number of Powerful Friends equal to your current Society Focus. You must specify the type and allegiance of each influential contact, but must also obtain the gamemaster’s approval for that selection. You may attempt a Daunting (D3) Society test to ask the selected contact for a favor. On a success, the contact responds with resources proportionate to their level of importance and the nature of the request. Any goods provided must be returned within a reasonable time limit: a period decided by the gamemaster but usually at the end of an adventure. You can attempt one such skill test during each period of downtime or in-play visit, taking a suitable amount of time to pleasantly broach the topic. Powerful Friends may be purchased multiple times, with each purchase establishing new contacts equal to your current Society Focus."
    },

    { name: "Reputation", max_ranks: 3,
      pre_skills: "", pre_talents: "A_Modicum_of_Comfort 1",
      description: "You have gained something of a reputation, and are often recognized by friends and foes alike. Each rank of Reputation increases your Renown by 1."
    },

    { name: "Wealthy", max_ranks: 3,
      pre_skills: "", pre_talents: "A_Modicum_of_Comfort 1",
      description: "You have squirreled away significant resources in long-term investments with multiple merchant families. Each rank of Wealthy grants 1 bonus Momentum for the express purpose of reducing the cost of any purchase, to a minimum of 1 Gold."
    }
  ],

  sorcery: [
    { name: "Delver in the Dark",
      pre_skills: "", pre_talents: "True_Understanding 1",
      description: "You have paid attention to the votaries of Skelos and know many secrets about dark forgotten places. When exploring old ruins, you may substitute Sorcery for Insight, Lore, or Thievery. Additionally, you may add 2 to Doom in order to substitute Sorcery for Athletics."
    },

    { name: "Demon Slayer",
      pre_skills: "", pre_talents: "Witch_Hunter 1",
      description: "You have learned how to most effectively harm and kill unnatural beings. When using the Witch Hunter talent, you can spend 1 Momentum to add Vicious 1 to your weapons (or increase the Vicious quality by 1 if your weapon already has the quality) against any sorcerers and unnatural entities present in the scene."
    },

    { name: "Patron",
      pre_skills: "sorcery 1 0", pre_talents: "",
      description: "You have obtained a patron, who will teach you the arts of sorcery. You may now purchase the Sorcerer talent and can begin to learn spells (see Chapter Seven: Sorcery for a list of all spells)."
    },

    { name: "Protective Superstitions", max_ranks: 3,
      pre_skills: "", pre_talents: "True_Understanding 1",
      description: "When involved in a Struggle to resist the effects of a spell, you gain one bonus Momentum per rank of Protective Superstitions."
    },

    { name: "Reader of the Book of Skelos",
      pre_skills: "", pre_talents: "Ritualist 1",
      description: "Your mind has been corrupted with detailed knowledge of places and deeds both foul and terrible. When using the Ritualist talent to assist another character, you may spend Momentum to buy bonus d20s to add to your roll for the teamwork test."
    },

    { name: "Ritualist",
      pre_skills: "", pre_talents: "True_Understanding 1",
      description: "You are well-versed in the sorcerous arts, understanding enough to assist true masters with their work. When performing teamwork tests or rituals using the Sorcery skill, you can assist with 2d20 rather than the normal d20 teamwork provides."
    },

    { name: "Sorcerer",
      pre_skills: "sorcery 2 0", pre_talents: "Patron 1",
      description: "Your character’s eyes are open to the horrible realities of the cosmos. Gain 1 spell and reduce the character’s resolve permanently by 0+[CD]2. See Chapter Seven: Sorcery for more details about this and other Sorcery talents."
    },

    { name: "True Understanding", max_ranks: 3,
      pre_skills: "sorcery 1 0", pre_talents: "",
      description: "You may pay 2 points of Resolve to gain 1 bonus Momentum on any Sorcery test other than tests to cast a spell. You may do this once per rank in this talent, paying up to 6 Resolve in this fashion."
    },

    { name: "Witch Hunter",
      pre_skills: "sorcery 2 0", pre_talents: "Protective_Superstitions 1",
      description: "You have turned your knowledge of the unnatural to the practical concern of saving your own life. In a combat where there is at least one sorcerer or unnatural creature on the opposing side, you may attempt a Daunting (D3) Sorcery test as a Standard Action. If successful, you gain 1[CD] extra Cover Soak against your foe’s attacks and powers. Momentum increases this Soak by +1[CD] (Repeatable)."
    }
  ],

  stealth: [
    { name: "Assassin",
      pre_skills: "", pre_talents: "Death_Dealer 1",
      description: "You are practiced in the art of murder, and taking lives no longer carries any emotional weight. When rolling damage with a melee weapon that has the Hidden quality, you may spend 2 points of Momentum in order to count every dice in the pool as an Effect, instead of whatever was actually rolled. Additionally, you gain +2[CD] Courage Soak."
    },

    { name: "Camouflage", max_ranks: 3,
      pre_skills: "stealth 2 0", pre_talents: "Living_Shadow 1",
      description: "It is important for you to remain concealed, but at times it is also important that your allies and any equipment they may be using also go unseen. You can apply your Stealth skill result to a number of other creatures or large objects equal to your Stealth Focus plus your ranks in Camouflage."
    },

    { name: "Death Dealer",
      pre_skills: "", pre_talents: "Many_Blades 1",
      description: "You are a proficient killer, relying on trickery and misdirection. When armed with any weapon that has the Hidden quality, you may substitute Stealth for your Melee and Ranged Weapons skills, and increase the damage of the weapon by +1[CD]."
    },

    { name: "Living Shadow",
      pre_skills: "stealth 1 0", pre_talents: "",
      description: "You are adept at using terrain effects and social cues to remain unnoticed by observers. When attempting to remain unseen or unnoticed, you gain bonus Momentum equal to the total number of your ranks in all your Stealth talents."
    },

    { name: "Many Blades",
      pre_skills: "", pre_talents: "Living_Shadow 1",
      description: "You always carry at least a dagger concealed somewhere. Even if you lose all your weaponry, you can add 1 to Doom and produce a concealed dagger as a Minor Action."
    },

    { name: "Master of Disguise",
      pre_skills: "", pre_talents: "Living_Shadow 1",
      description: "You know how to impersonate others, whether to blend into the background or to appear as a specific person. When you succeed at a Stealth test to create a disguise, you gain bonus Momentum equal to the amount of Momentum generated on that test (in essence, every point of Momentum generated by the test is doubled). In addition to this, if the disguise is to impersonate another, you may substitute your Stealth skill for Persuade or Command."
    },

    { name: "Obscure Trail",
      pre_skills: "", pre_talents: "Camouflage 1",
      description: "You know a variety of tricks to make it substantially harder for someone to follow you. When you suspect (or fear) that you might be followed, you may make an Average (D1) Stealth test. The Difficulty for any pursuer’s test to follow you is increased by one step, plus an additional step for each Momentum spent (Repeatable)."
    },

    { name: "Perfect Ambush",
      pre_skills: "", pre_talents: "Master_of_Disguise 1",
      description: "You have such mastery of stealth and subterfuge that you can perform an ambush with little-to-no preparation. When you perform an ambush, you can voluntarily make the ambush harder to pull off, and in doing so make it almost impossible to detect. When you attempt an ambush or surprise, you may increase the Difficulty of your Stealth test by one or two steps. The Difficulty of the enemy’s Observation test to spot the ambush increases by two steps for every step of increase you accepted."
    }
  ],

  survival: [
    { name: "Born Wild",
      pre_skills: "survival 1 0", pre_talents: "",
      description: "You can reduce the Difficulty of any Survival test to find food and shelter by one step, to a minimum of Simple (D0). Born Wild is factored into the difficulties of all Survival talents."
    },

    { name: "Hunter",
      pre_skills: "", pre_talents: "Tracker 1",
      description: "You have learned to anticipate the movements of prey. When making a Survival test to track a creature or group of creatures, you may spend 2 Momentum or add 2 to Doom to find a shortcut or other way of intercepting the creatures being tracked. You may also substitute Survival for Stealth when attempting to ambush creatures being tracked."
    },

    { name: "Living Off the Land",
      pre_skills: "", pre_talents: "Born_Wild 1",
      description: "You are particularly capable of finding the necessities of life. When attempting a Survival test to find food, water, or shelter, each point of Momentum spent (Repeatable) provides these necessities for two other creatures (allies, tame animals, etc.). If you are in your own homeland or some other territory you are extremely familiar with, the basic Difficulty of Survival tests to find food, water, and shelter is reduced to Simple (D0), and every point of Momentum spent (Repeatable) finds these necessities for three additional creatures, rather than two."
    },

    { name: "Predator",
      pre_skills: "survival 99 99", pre_talents: "Hunter 1",
      description: "UNKNOWN -- DETAILS NOT IN PREVIEW CHAPTER"
    },

    { name: "Risks", max_ranks: 11,
      pre_skills: "", pre_talents: "Born_Wild 1",
      description: "You are familiar with various environmental hazards presented by the wilderness. Choose one environment when this talent is purchased, and any time you travel within a particular kind of environment you may attempt an Average (D1) Survival test. On a success, you are able to avoid all implicit dangers, potentially avoiding dangerous encounters. Each point of Momentum may be spent to protect one of your allies from these same risks. Further ranks in this talent add new environment types. Possible environments are: Arctic, Coastal, Desert, Jungle, Mountain, Forest, Plains, Steppes, Subterranean, Urban, or another if permitted by the gamemaster."
    },

    { name: "Remedies and Rewards",
      pre_skills: "survival 2 0", pre_talents: "Risks 1",
      description: "You know various natural or traditional remedies for illness and sickness that can be found in the wild. When outside of the city, you may substitute your Survival skill for Healing or Alchemy. Additionally, when travelling through the wilderness, you may make a Challenging (D2) Survival test once per journey. Each point of Momentum achieved provides 1 poultice for use in treating wounds."
    },

    { name: "Tracker", max_ranks: 3,
      pre_skills: "", pre_talents: "Born_Wild 1",
      description: "You can recognize all the signs of passage, from the subtle to the obvious, and have become particularly adept at following a target. When attempting a Survival test to track a creature or group of creatures, you may reduce the Difficulty of the test by one step for every rank of Tracker."
    }
  ],

  thievery: [
    { name: "Appraisal",
      pre_skills: "", pre_talents: "Easy_Money 1",
      description: "You have robbed many people, and over time learned the difference between valuable items and those that merely look valuable. You instinctively know the difference between real treasure and fake baubles and know to forgo lesser rewards for greater ones. When looking over valuable items to determine their worth and provenance, you may substitute Thievery for Insight or Lore. Further, when using the Easy Money talent, you may gain one additional Gold by adding 2 to Doom instead of 3, and you may use this benefit twice on any given criminal act."
    },

    { name: "Burglar",
      pre_skills: "thievery 0 2", pre_talents: "Walk_In,_Walk_Out 1",
      description: "You have made a career of entering the towers, homes, and palaces of the wealthy. You’ve experienced tall walls, cunning traps, and strange locks, and have developed a broad range of different techniques to overcome them all. Any time you attempt to enter or leave a property with larceny in mind, you may add 1 to Doom in order to substitute Thievery for any other skill except Alchemy or Sorcery."
    },

    { name: "Easy Money",
      pre_skills: "", pre_talents: "Thief 1",
      description: "You are particularly astute at recognising profitable opportunities such as picking pockets, short cons, and other minor crimes. You may substitute your Thievery skill for Observation on any tests that are related to committing a crime. In addition, whenever you steal or otherwise obtain money by illicit means, you may add 3 to Doom in order to gain 1 additional Gold from that particular crime (and only one additional Gold)."
    },

    { name: "Master Thief",
      pre_skills: "", pre_talents: "Thief 1",
      description: "You may re-roll one d20 when making a Thievery test, but you must accept the new result."
    },

    { name: "Thief",
      pre_skills: "thievery 1 0", pre_talents: "",
      description: "After years of dealing with the criminal underworld, you have a basic familiarity of how to interact with this segment of the population. You may use Thievery in place of Society when dealing with criminals. When you generate at least one success on a Persuade or Lore test to relate to or interact with the criminal element, you may immediately roll one additional d20 and add the result to the skill test."
    },

    { name: "Underworld Lore",
      pre_skills: "", pre_talents: "Thief 1",
      description: "You have listened to your elders and know many tales of amazing scores and terrible calamities. When considering a theft of any sort, you may spend 1 Momentum (Immediate) to know the fate of the last thief who attempted a similar act, and any precautions the target is likely to have taken since. Additionally, whenever studying the activities, traditions, taboos, and histories of a region’s criminal underworld, you may substitute Thievery for Insight, Lore, or Observation."
    },

    { name: "Walk In, Walk Out",
      pre_skills: "", pre_talents: "Master_Thief 1",
      description: "Committing a crime is easy: getting away with it is harder. Through practice, you have learned how to avoid notice by blending in with the crowd. You may substitute your Thievery skill for Stealth when attempting any criminal act."
    }
  ]

  fortune: [
    { name: "Better Lucky than Dead",
      pre_skills: "", pre_talents: "Make_Your_Own_Luck 1",
      description: "Whenever you suffer a Wound or Trauma, you may spend 1 Fortune point to ignore it entirely. In this case, the Wound or Trauma simply does not happen, though the attack inflicts damage normally in all other regards."
    },

    { name: "Fickle Fortune",
      pre_skills: "", pre_talents: "Make_Your_Own_Luck 1",
      description: "ou are always gambling with fate and fortune, and willing to take a chance on a better reward. You may spend 1 Fortune point to gain three bonus d20s on a skill test, rolled normally (the normal limit of three bonus d20s still applies), instead of simply specifying a single d20 with a “1” for a result. This choice can be made on a case-by-case basis: 1 Fortune point is spent for each instance."
    },

    { name: "Lucky Charm",
      pre_skills: "", pre_talents: "Make_Your_Own_Luck 1",
      description: "You carry a trinket, talisman, or some other small item of superstitious worth, which must be specified when this talent is purchased. It may not be anything so large that it cannot be carried in one hand. While this item is on your person, whenever you spend a Fortune point, roll 1[CD]. If an Effect is rolled, you gain the benefit of the Fortune point, but the Fortune point itself is not spent and returns to you."
    },

    { name: "Make Your Own Luck",
      pre_skills: "", pre_talents: "",
      description: "You have little care for the vagaries of luck, and create your own advantages in life, whatever the cost or risk. You may spend 3 Momentum (Immediate) to gain the benefits of 1 Fortune point. Remember that Immediate Momentum spends can be paid for by adding to Doom instead of spending Momentum."
    }
  ]

  homeland: [
    { name:
      pre_skills: "", pre_talents: "",
      description: ""
    },
  ]

  caste: [
    { name:
      pre_skills: "", pre_talents: "",
      description: ""
    },
  ]

}

homelands = {
  land: { talent: , language: },
}

castes = {

}

caste_stories = {

}

archetypes = {

}

educations = {

}

natures = {

}

war_stories = {

}

weapons = {

}
